apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5waW50ZWNocy5jb20iOnsidXNlcm5hbWUiOiJjYWlqaWFjaGVuIiwicGFzc3dvcmQiOiJBQXNzMTIzNCIsImF1dGgiOiJZMkZwYW1saFkyaGxianBCUVhOek1USXpOQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-07-14T08:01:03Z"
  name: harbor-credentials
  namespace: yatai-deployment
  resourceVersion: "14124028"
  uid: ff8b4797-8c77-40d5-afeb-6008bb043f92
type: kubernetes.io/dockerconfigjson
