apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5waW50ZWNocy5jb20iOnsidXNlcm5hbWUiOiJjYWlqaWFjaGVuIiwicGFzc3dvcmQiOiJBQXNzMTIzNCIsImF1dGgiOiJZMkZwYW1saFkyaGxianBCUVhOek1USXpOQT09In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-07-17T02:12:48Z"
  name: harbor-credentials
  namespace: yatai-image-builder
  resourceVersion: "14758446"
  uid: 30e58c86-0fd8-4253-a30a-f02ece43970e
type: kubernetes.io/dockerconfigjson
