FROM vllm/vllm-openai:latest

COPY requirements.txt /tmp/requirements.txt

RUN python3 -m pip install -r /tmp/requirements.txt

WORKDIR /bentoml-workspace

VOLUME ["/bentoml-workspace"]

ENTRYPOINT ["bash", "-lc", "bentoml serve --arg-file ./conf.yaml"]
