FROM vllm/vllm-openai:latest

RUN python3 -m pip install bentoml==1.4.33

WORKDIR /bentoml-workspace

VOLUME ["/bentoml-workspace"]

ENTRYPOINT ["bash", "-lc", "bentoml serve --arg-file ./conf.yaml"]
