apiVersion: resources.yatai.ai/v1alpha1
kind: BentoRequest
metadata:
  name: qwen3-8b
  namespace: yatai
spec:
  bentoTag: qwen3-8b:latest
  ociRegistryInsecure: true
  imageBuilderContainerResources:
    requests:
      cpu: "4"
      memory: "16Gi"
      ephemeral-storage: "50Gi"
    limits:
      cpu: "8"
      memory: "32Gi"