apiVersion: v1
kind: ConfigMap
metadata:
  name: bento-config
  namespace: yatai
data:
  BENTO_CLOUD_API_ENDPOINT: http://yatai.yatai-system.svc.cluster.local
  BENTO_CLOUD_API_KEY: d87uul00scps73d7c2f0
