[project]
name = "bentosglang"
version = "0.1.0"
description = "Self-host LLMs with SGLang and BentoML"
requires-python = ">=3.12.0"

[tool.bentoml.build]
service = "service.py:SGL"
include = [
  "*.py",
  "*.toml",
  "*.txt",
  "uv.lock",
  "*.yaml",
]

[tool.bentoml.build.python]
requirements_txt = "./requirements.txt"
index_url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.bentoml.build.docker]
base_image = "lmsysorg/sglang:v0.5.17"
dockerfile_template= "./Dockerfile.template.j2"
