{% extends "base.j2" %}

{% block SETUP_BENTO_USER %}
{% endblock %}

{% block SETUP_BENTO_ENVARS %}

ARG BENTO_PATH=/app
ENV BENTO_PATH=$BENTO_PATH
ENV BENTOML_HOME={{ bento__home }}
ENV BENTOML_HF_CACHE_DIR=/app/hf-models
ENV BENTOML_CONTAINERIZED=true

WORKDIR /app

{% endblock %}

{% block SETUP_BENTO_COMPONENTS %}

# Block SETUP_BENTO_COMPONENTS
COPY --chown=root:root ./env/python/requirements.txt ./env/python/requirements.txt

# mount=type=cache 让 pip 缓存持久化（跨 build 复用）
RUN --mount=type=cache,target=/root/.cache/pip \
    python3 -m pip install -r ./env/python/requirements.txt \
    --index-url https://mirrors.aliyun.com/pypi/simple/

COPY --chown=root:root ./env/python ./env/python/
COPY --chown=root:root . ./

{% endblock %}

{% block SETUP_BENTO_ENTRYPOINT %}
EXPOSE 3000
EXPOSE {{ __prometheus_port__ }}

ENTRYPOINT [ "bentoml", "serve", "/app" ]

{% endblock %}
