FROM registry.pintechs.com/cg-img-base/vllm/vllm-openai:v0.25.1
LABEL org.opencontainers.image.system_version="Ubuntu 22.04.5 LTS" \
      org.opencontainers.image.python_version="3.12" \
      org.opencontainers.image.CUDA_version="13.0" \
      org.opencontainers.image.infer_engine="vLLM 0.25" \
      org.opencontainers.image.remark=""
