FROM vllm/vllm-openai:minimax27
LABEL org.opencontainers.image.system_version="Ubuntu 22.04.5 LTS" \
      org.opencontainers.image.python_version="3.12" \
      org.opencontainers.image.CUDA_version="12.9" \
      org.opencontainers.image.infer_engine="vLLM 0.19" \
      org.opencontainers.image.remark="minimax m2.7"