FROM voipmonitor/sglang:cu130
LABEL org.opencontainers.image.system_version="Ubuntu 24.04.3 LTS" \
      org.opencontainers.image.python_version="3.12" \
      org.opencontainers.image.CUDA_version="13.0" \
      org.opencontainers.image.infer_engine="SGLang blackwell-cu130@f7a239a" \
      org.opencontainers.image.remark="qwen3.5 397b nvfp4"