FROM sglang-blackwell:sm120a-tfv5

RUN python3 -m pip install bentoml
ENV BENTO_NAME=qwen3.5 \
    BENTO_TAG=1.0.0

WORKDIR /bentoml-workspace

VOLUME ["/bentoml-workspace"]

ENTRYPOINT ["bash", "-lc", "bentoml serve --arg-file ./conf.yaml"]
