FROM sglang-blackwell:sm120a-tfv5

RUN python3 -m pip install bentoml
ENV BENTO_NAME=qwen3.5 \
    BENTO_TAG=1.0.0

WORKDIR /bentoml-workspace
VOLUME ["/bentoml-workspace"]
COPY service.py conf.yaml ./
RUN http_proxy=http://172.17.0.1:7890/ https_proxy=http://172.17.0.1:7890/ bentoml build --arg-file ./conf.yaml --name ${BENTO_NAME} --version ${BENTO_TAG}
ENTRYPOINT ["bash", "-lc", "bentoml serve ${BENTO_NAME}:${BENTO_TAG}"]
