apiVersion: resources.yatai.ai/v1alpha1
kind: BentoRequest
metadata:
  name: ${BENTO_NAME}
  namespace: ${BENTO_NAMESPACE:-yatai}
spec:
  bentoTag: ${BENTO_NAME}:${BENTO_VERSION}
  ociRegistryInsecure: true
  imageBuilderContainerResources:
    requests:
      cpu: "4"
      memory: "16Gi"
      ephemeral-storage: "50Gi"
    limits:
      cpu: "8"
      memory: "32Gi"