apiVersion: v1
kind: ConfigMap
metadata:
  name: yatai-cloud-config
  namespace: ${BENTO_NAMESPACE:-yatai}
data:
  BENTO_CLOUD_API_ENDPOINT: ${BENTO_CLOUD_API_ENDPOINT}
  BENTO_CLOUD_API_KEY: ${BENTO_CLOUD_API_KEY}
